channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python>=3.9
  - conda-forge::pyyaml
  - bioconda::samtools=1.23
  - bioconda::minimap2=2.30
  - bioconda::bwa
  - bioconda::bwa-mem2=2.3
  - bioconda::skani
  - bioconda::fastani
  - bioconda::strobealign
